name: CI/CD - Build and Deploy to GCP Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: fleet-authority-464619-k7
  REGION: us-central1
  SERVICE_NAME: text-to-image-service
  IMAGE: gcr.io/fleet-authority-464619-k7/text-to-image-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate Docker with GCR
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t $IMAGE .

    - name: Push Docker image
      run: docker push $IMAGE

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image $IMAGE \
          --region ${{ env.REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"

